version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    target-branch: develop
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    target-branch: develop
